# Generated by Django 5.0 on 2025-09-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
